# Generated by Django 3.0.3 on 2020-07-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgt', '0006_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
